site_name: SFI - Svenska för invandrare
site_url: https://ophoria.github.io/SFI/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
  language: sv

extra_css:
  - stylesheets/extra.css
